### PR TITLE
Remove Docker Debug Log from logrotate

### PR DESCRIPTION
**Pull request by JKTUNING**
Remove unused log rotate for Docker Debug log.

### CODE REVIEW

**Review by TechDufus — APPROVED** [review]
LGTM, ship it

**Review by TechDufus — COMMENTED** [review]
On 2nd thought, this won't actually `purge` the rule that already exists that this has already created on nodes.

**Comment by JKTUNING** [comment]
@TechDufus adding legacy files/folders to check during purge. Including update to vars file.

https://github.com/TechDufus/FluxNodeInstall/blob/913a8d9a4986088009cac2ae8b2c6400083ceb6f/roles/logrotate/tasks/logrotate-purge.yml#L9

**Comment by TechDufus** [comment]
> @TechDufus adding legacy files/folders to check during purge. Including update to vars file.
> 
> https://github.com/TechDufus/FluxNodeInstall/blob/913a8d9a4986088009cac2ae8b2c6400083ceb6f/roles/logrotate/tasks/logrotate-purge.yml#L9

This will only be 'cleaned up' if a purge is ran though, correct?

**Comment by JKTUNING** [comment]
> > @TechDufus adding legacy files/folders to check during purge. Including update to vars file.
> > https://github.com/TechDufus/FluxNodeInstall/blob/913a8d9a4986088009cac2ae8b2c6400083ceb6f/roles/logrotate/tasks/logrotate-purge.yml#L9
> 
> This will only be 'cleaned up' if a purge is ran though, correct?

Yes, I suppose we can just tack a remove at the end of the install to ensure any "Legacy" files are cleaned up/removed.

**Pull request merged**
